import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { MainNavbar } from '@/components/Navbar';
import Footer from '@/components/Footer';
import { ToastProvider } from '@heroui/react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased light`}
      data-theme="light"
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-slate-50 text-slate-900 font-sans">
        <MainNavbar />
        <main className="grow">{children}
          <ToastProvider/>
        </main>

        <Footer />
      </body>
    </html>
  );
}
